### ISSUE TITLE
GMEXT-MLKit: [iOS] Unable to run the demo extension project

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GMEXT-MLKit#2]
### Description

As of Beta IDE v2024.1100.0.710  Runtime v2024.1100.0.726 when targeting iOS the extension project fails to build with the following error:

```
The following build commands failed:
	CompileC /Users/emontes/Library/Developer/Xcode/DerivedData/MLKit_Ext_v0_0_1-ammixmivjdgyklccdzctoofxqimj/Build/Intermediates.noindex/MLKit_Ext_v0_0_1.build/Debug-iphonesimulator/MLKit_Ext_v0_0_1.build/Objects-normal/x86_64/MLKit.o /Users/emontes/GameMakerStudio2/GM_IOS/MLKit.Ext.v0.0.1/MLKit_Ext_v0_0_1/MLKit_Ext_v0_0_1/Game/iOSSource/MLKit.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'MLKit_Ext_v0_0_1' from project 'MLKit_Ext_v0_0_1')
	Testing workspace MLKit_Ext_v0_0_1 with scheme MLKit_Ext_v0_0_1
(2 failures)
System.Exception: xcodebuild command exited with status 65
   at Igor.XCodeOutputReader.Process(TextWriter _out)
   at Igor.MacUtils.iosSendAndRunXCode(String workingFolder, String _dir, String _debugTargetIP, Boolean bForYYC, String _certificate, String _platform, String targetDevice, String lastTargetDevice, Boolean _suppressBuild, String projectName, YYDictionary`2 PlatformOptions, String yydebugFile, String remote_install_path, Boolean _podfilePresent)
   at Igor.iOSBuilder.RunYYC()
   at Igor.iOSBuilder.Run()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Igor complete.
```

MacOS Sequoia / Xcode 16.1 

[outputlog.txt](https://github.com/user-attachments/files/18095211/outputlog.txt)

### Steps To Reproduce

1. Start GameMaker
2. Import the last version of the extension 
3. Run targetting iOS VM/YYC
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta

### Which platform(s) are you seeing the problem on?

iOS

### Compiler Log File

- [x] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by jzavala-YYG** [comment]
dd9ea31dced34d356ffde8cc333b03aff541baed
